# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Kaiserlin/Desktop/COA/zhangs/SCCPU_FPGA/SCCPU_SOC.srcs/sources_1/ip/imem/imem.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==imem || ORIG_REF_NAME==imem} -quiet] -quiet
