# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Desktop/COA/newtry/PLCPU_FPGA/PLCPU_FPGA.srcs/sources_1/ip/imem/imem.xci
# IP: The module: 'imem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Desktop/COA/newtry/PLCPU_FPGA/PLCPU_FPGA.gen/sources_1/ip/imem/imem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'imem'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/Desktop/COA/newtry/PLCPU_FPGA/PLCPU_FPGA.srcs/sources_1/ip/imem/imem.xci
# IP: The module: 'imem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Desktop/COA/newtry/PLCPU_FPGA/PLCPU_FPGA.gen/sources_1/ip/imem/imem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'imem'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
